[phases.setup]
  nixPkgs = ['nodejs_20']
  nixpkgsArchive = '9684b531'
  providers = ['node']

[phases.install]
  cmds = ['npm install']

[phases.build]
  cmds = ['npm run build']

[start]
  cmd = 'npm run preview'
